#CICD/frontend/deployment.yaml
#test

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindlog-fe-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindlog-fe
  template:
    metadata:
      labels:
        app: mindlog-fe
    spec:
      containers:
      - name: frontend
        # --- [Dynamic] ---------------------------------
        image: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/mindlog-fe:latest
        ports:
        - containerPort: 3000
        env:
        # --- [Static] ----------------------------------
        - name: NODE_ENV
          value: "development"
        # --- [Dynamic] ---------------------------------
        - name: BACKEND_URL
          value: "${BE_API_URL}"
        # -----------------------------------------------

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
