apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindlog-be-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindlog-be
  template:
    metadata:
      labels:
        app: mindlog-be
    spec:
      containers:
      - name: backend
        image: <JENKINS_FILL_BE_IMAGE_HERE>
        ports:
        - containerPort: 8080 # 보통 백엔드(Spring/Django 등)는 8080을 많이 써요
