#CICD/backend/deployment.yaml
# test

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindlog-be-deployment
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mindlog-be
  template:
    metadata:
      labels:
        app: mindlog-be
    spec:
      containers:
      - name: backend
        image: ${ECR_URL}/mindlog-be:latest
        ports:
        - containerPort: 8080
        
        env:
        - name: PROFILE
          value: "dev"
        - name: DB_DEV_PORT
          value: "5432"
        - name: DB_DEV_DATABASE
          value: "testdb"      
        - name: DB_DEV_USERNAME
          value: "dbadmin"     
        - name: REDIS_DEV_PORT
          value: "6379"
        - name: AWS_S3_BUCKET_NAME
          value: "test-project-test-photos" 
        - name: AWS_REGION
          value: "ap-northeast-2"
        # --- [Dynamic] ---------------------------------
        - name: DB_DEV_HOST
          value: "${RDS_ENDPOINT}"
        - name: REDIS_DEV_HOST
          value: "${REDIS_ENDPOINT}"
        - name: SPRING_DATA_REDIS_HOST
          value: "${REDIS_ENDPOINT}"
        # --- [Secret] ---------------------------------
        - name: DB_DEV_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mindlog-be-secret
              key: DB_PASSWORD 
        - name: KT_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mindlog-be-secret
              key: KT_JWT_SECRET
              
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
