apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindlog-be-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindlog-be
  template:
    metadata:
      labels:
        app: mindlog-be
    spec:
      containers:
      - name: backend
        # ECR 생성 후 실제 주소로 교체
        image: 8ocket-prod-be-repo:tmp
        ports:
        - containerPort: 8080
        env: 
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://rds-prod-8ocket.xxxx.ap-northeast-2.rds.amazonaws.com:5432/mindLogDB"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "현웅님께_물어볼_비번"
        - name: SPRING_DATA_REDIS_HOST
          value: "valkey-prod-8ocket.xxxx.cache.amazonaws.com"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"

        # 헬스체크 
        livenessProbe: 
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60 
          periodSeconds: 30
        readinessProbe: 
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
