global:
  licenseKey: ""
  customSecretName: "mindlog-be-secret"
  customSecretLicenseKey: "LICENSE_KEY"
  cluster: "mindlog"

newrelic-infrastructure:
  enabled: false

kube-state-metrics:
  enabled: false

logging:
  enabled: false

prometheus:
  enabled: false

k8s-agents-operator:
  enabled: true   # 켜둬야 함

k8s-agents-operator-instrumentation:
  enabled: true   # 켜둬야 함
