apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindlog-ai-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ai-api
        image: <ECR주소>/mindlog-ai:latest # 나중에 주소 교체
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            value: "PENDING_RDS_ENDPOINT" # 테라폼 완료 후 수정 예정
          - name: REDIS_URL
            value: "PENDING_VALKEY_ENDPOINT"
        # 헬스체크 
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
