name: Build and Deploy Action

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SERVICE: ${{ inputs.service_name }}
        run: |
          
          if [ -f "Makefile" ]; then
            make ecr-build ECR_REPO=$SERVICE
            docker tag $SERVICE:latest $ECR_REGISTRY/$SERVICE:latest
            docker push $ECR_REGISTRY/$SERVICE:latest
          
          else
            docker build \
              -t $ECR_REGISTRY/$SERVICE:latest .
            docker push $ECR_REGISTRY/$SERVICE:latest
          fi
      - name: Trigger Deploy
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.CICD_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/8ocket/cicd/dispatches \
            -d '{"event_type":"deploy"}'


