name: Deploy

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Execute Deployment on Local Path
        run: |
          cd ~/cicd
          git fetch origin
          git reset --hard origin/main
          chmod +x ./setup-secrets.sh
          chmod +x ./deploy.sh
          ./deploy.sh


